#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

ARROW="\033[93m==>\033[0m"

echo -e "$ARROW black worf --check"
black worf --check

echo -e "$ARROW flake8 worf"
flake8 worf

echo -e "$ARROW isort worf --check"
isort worf --check
