#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

ARROW="\033[93m==>\033[0m"

echo -e "$ARROW black worf tests --check"
black worf tests --check

echo -e "$ARROW flake8 worf tests"
flake8 worf tests

echo -e "$ARROW isort worf tests --check"
isort worf tests --check
