#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

ARROW="\033[93m==>\033[0m"

echo -e "$ARROW autoflake --in-place --recursive --remove-all-unused-imports worf tests"
autoflake --in-place --recursive --remove-all-unused-imports worf tests

echo -e "$ARROW black worf tests"
black worf tests

echo -e "$ARROW flake8 worf tests"
flake8 worf tests

echo -e "$ARROW isort worf tests"
isort worf tests
