#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

ARROW="\033[93m==>\033[0m"

echo -e "$ARROW autoflake --in-place --recursive --remove-all-unused-imports worf"
autoflake --in-place --recursive --remove-all-unused-imports worf

echo -e "$ARROW black worf"
black worf

echo -e "$ARROW flake8 worf"
flake8 worf

echo -e "$ARROW isort worf"
isort worf
