#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

CURRENT_VERSION="$(git tag --sort=v:refname | tail -1)"

./bin/pipenv run python3 -m build
./bin/pipenv run python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p $TWINE_PASSWORD
