#!/bin/bash

set -euxo pipefail
cd "$(dirname "$0")/.."

CURRENT_VERSION="$(git tag --sort=v:refname | tail -1)"

build() {
  # If old versions are present in dist it will die on upload
  echo "building"
  if [ -d dist ]; then
    rm dist/* || rmdir dist
  fi
  ./bin/pipenv run python3 -m build
}

if [ "$(ls -l dist/ | wc -l)" -ne 3 ]; then
  build
elif [ ! -z ${1+x} ] && [ $1 == "--build" ]; then
  build  # Build on explict build command
fi


if [ ! -z ${1+x} ] && [ $1 == "--force" ]; then
  ./bin/pipenv run python3 -m twine upload dist/* -u __token__ -p $TWINE_PASSWORD
else
  ./bin/pipenv run python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p $TWINE_PASSWORD
fi
