#!/bin/bash

set -eou pipefail
cd "$(dirname "$0")/.."

CURRENT_VERSION="$(git tag --sort=v:refname | tail -1)"
git tag -d $CURRENT_VERSION
vim CHANGELOG.md
git add CHANGELOG.md
git commit --amend --no-edit --no-verify
git tag $CURRENT_VERSION

echo "__version__ = \"${CURRENT_VERSION}\""
