#!/bin/bash

cd "$(dirname "$0")/.."
set -eou pipefail

play_success() {
  case $OSTYPE in
  darwin*)
    say -v yuri -r 10 "Tests have passed"
  ;;
  esac
  echo "==> Tests Passed ⛵️"
}
play_fail() {
  case $OSTYPE in
  darwin*)
    for i in {1..5}; do afplay /System/Library/Sounds/Pop.aiff; done
  ;;
  esac
  echo "==> Tests Failed 💥"
  exit 1
}

bin/pytest \
  && play_success || play_fail
