name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.lock"
      - "**/*.md"
      - worf/__init__.py

  push:
    branches:
      - master
      - package-updates

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  # cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, "3.10", "3.11"]
        django: [3.2, "4.0", 4.1]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install pipenv
      - run: pipenv install --dev --python ${{ matrix.python }}
      - run: pipenv install django~=${{ matrix.django }} --skip-lock
      - run: pipenv run pytest --cov

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install pipenv
      - run: pipenv run install_linters
      - run: pipenv run check
