name: CI

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.8
      - run: pip install pipenv
      - run: pipenv install --dev --python 3.8.8
      - run: pipenv run pytest
