name: CI

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        django: ["3.0", 3.1, 3.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - run: pip install pipenv
      - run: pipenv install --dev --python ${{matrix.python}}
      - run: pipenv install django~=${{matrix.django}}
      - run: pipenv run pytest --cov

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.8
      - run: pip install black flake8
      - run: black worf --check
      - run: flake8 worf
